"""Single source of truth for the NotebookGame art direction.

Every asset in this game is generated by Azure OpenAI **gpt-image-2**. Visual
consistency comes from one rule: no prompt is ever sent raw. Every prompt is
composed as ``STYLE_PREFIX + subject + STYLE_SUFFIX``, so the model receives an
identical style contract on every single call.

If you want to change the look of the game, change it *here* and regenerate.
Do not tweak style words inside individual asset prompts.
"""

# --- The style contract -----------------------------------------------------

STYLE_PREFIX = (
    "Loose childlike hand-drawn doodle in black ink on light gray paper. "
    "Thick bold wobbly marker outlines of uneven weight, chunky simple shapes, "
    "minimal detail, goofy and playful. Halftone dot texture and light "
    "cross-hatching for all shading. "
    "Strictly monochrome black and white, absolutely no color, no gradients. "
    "Naive sketchbook margin-doodle aesthetic, as if drawn by hand in the "
    "margin of a school notebook. Top-down three-quarter view video game asset. "
    "Subject: "
)

STYLE_SUFFIX = (
    " Flat plain background, no scenery behind the subject, no ground plane, "
    "no frame, no border, no text, no letters, no watermark, no signature, "
    "no color of any kind."
)

# Living things and scenery in this world are alive and friendly-looking.
FACE_RULE = (
    " It has a cute tiny face with two small dot eyes and a simple curved smile."
)

# Character sheets need a rigid layout or SpriteKit cannot slice them.
def sheet_rule(cols: int, rows: int) -> str:
    return (
        f" Arrange exactly {cols * rows} separate poses in a strict, evenly "
        f"spaced {cols} column by {rows} row grid. Every pose is the same "
        "character at the exact same size and the exact same vertical "
        "position within its cell, centered in its cell, with generous even "
        "margins. No grid lines, no numbering, no captions, no boxes."
    )


def build_prompt(subject: str, *, face: bool = False, sheet: tuple[int, int] | None = None) -> str:
    """Compose a full prompt from a bare subject description."""
    parts = [STYLE_PREFIX, subject.strip().rstrip(".") + "."]
    if face:
        parts.append(FACE_RULE)
    if sheet:
        parts.append(sheet_rule(*sheet))
    parts.append(STYLE_SUFFIX)
    return "".join(parts)


# --- Redrawing an existing character ----------------------------------------

# Words alone cannot pin an identity down. Asking gpt-image-2 four separate
# times for "the same spiky-haired kid" yields four different kids, which is
# exactly why the hero used to morph between walking, idling and fighting.
# These prompts go to the /images/edits endpoint with the canonical drawing
# attached, so the model is copying rather than inventing.
REFERENCE_PREFIX = (
    "Redraw the exact character from the attached picture, keeping their "
    "identity completely unchanged: same hairstyle, same face, same clothing, "
    "same shoulder strap and buckle, same backpack, same boots, same "
    "proportions, same body size, same ink line weight and same halftone "
    "shading. Do not redesign, restyle, age or replace the character, and do "
    "not add or remove any equipment. Only the pose and the viewing angle may "
    "change. New pose: "
)

REFERENCE_SUFFIX = (
    " Keep the loose childlike hand-drawn doodle look in black ink on light "
    "gray paper, thick wobbly marker outlines, halftone dot shading, strictly "
    "monochrome black and white with absolutely no color. Flat plain "
    "background, no scenery, no ground plane, no frame, no border, no text, "
    "no watermark."
)


def build_reference_prompt(subject: str, *, sheet: tuple[int, int] | None = None) -> str:
    """Compose a prompt that re-poses the character in the attached reference."""
    parts = [REFERENCE_PREFIX, subject.strip().rstrip(".") + "."]
    if sheet:
        parts.append(sheet_rule(*sheet))
        parts.append(
            " Every single pose in the grid is that same one character, "
            "identical in design to the attached picture."
        )
    parts.append(REFERENCE_SUFFIX)
    return "".join(parts)


# --- Generation defaults ----------------------------------------------------

DEFAULT_SIZE = "1024x1024"
WIDE_SIZE = "1536x1024"
TALL_SIZE = "1024x1536"
DEFAULT_QUALITY = "high"
